### ISSUE TITLE
support for facebook, twitter

### ISSUE THREAD

**Issue by berndhopp** [mikotin/google-signin#1]
these should be the 'big three' of oauth-providers. would it be possible to provide similar buttons for them, too?

**Comment by mikotin** [comment]
Aye, that's the goal. Making (at least) those and then some "umbrella" -component to gather those and provide common api. 
Would you happen to know if there are good web-components available for those? Or any interest of creating one? I'm looking forward to create those myself (but it takes some time, so any ready made / help would come handy)

**Comment by berndhopp** [comment]
this facebook-login one looks good to me

https://libraries.io/bower/facebook-login

I cant make any promises, but when I find some time in between projects, I may be able to contribute. Beforehand, it would be nice if you could extract an interface from GoogleSignin, like 'Signin' with the API you expect from all Signin-buttons, I guess everything from between line 189 and 228 in GoogleSignin.

**Comment by berndhopp** [comment]
Could you take a look at https://github.com/berndhopp/Joscha?
it's not working yet, but it's my attempt to create a General oauth Implementation for vaadin, based on oauth.io and scribe for Client and Server oauth. Since it's almost a complete rewrite, I Took the freedom to name it after my son. The issue that curently Stalls my progress is this one:https://vaadin.com/forum/thread/17369771. But this Project needs a lot of work anyways, so maybe you want to join forces here.

Best
Bernd
