### ISSUE TITLE
TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by poczenorbert** [mikotin/google-signin#2]
I get TypeError: Cannot read property 'appendChild' of null :google-signin-aware.html:236  when using vaadin version 10.0.0.beta11  or  10.0.2

No error with vaadin version 10.0.0.beta10

**Comment by mikotin** [comment]
Thank you for noticing. Seems like problem with newer Flow version, but not sure yet. I'll take a look on this.

**Comment by mikotin** [comment]
A workaround is now in latest version. Please give it a try.

**Comment by poczenorbert** [comment]
It  works, thanks.

**Comment by mikotin** [comment]
Very good. Thanks for informing and testing.

**Comment by poczenorbert** [comment]
I still have the error with vaadin.productionMode = true
My previous test was in development/debug mode with success.
